name: driving_guidelines
description: A summary of the medical standards for licensing in Australia

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaml: ^3.1.1
  path: ^1.8.0
  shared_preferences: ^2.0.15
  webview_flutter: ^4.7.0
  url_launcher: ^6.1.2
  provider: ^6.0.3
  flutter_markdown: ^0.6.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.0

flutter_native_splash:
  color: '#26a69a'
  image: assets/icons/app_logo_1024.png
  android_12:
    color: '#26a69a'
    image: assets/icons/app_logo_1024.png

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path: 'assets/icons/app_logo_512.png'

flutter:
  assets:
    - assets/data/
    - assets/guidelines/
    - assets/icons/

  uses-material-design: true
